### ISSUE TITLE
Support partial visibility

### ISSUE THREAD

**Issue by AndersDJohnson** [KyleAMathews/react-headroom#115]
Can we support partial visibility of the headroom contents at all time? So the header is always visible but expands/contracts dynamically.

I tried implementing with a combination of custom styles an the `pinStart` attribute:
```css
.headroom--unpinned {
  transform: translateY(-50%);
}
```
But the snap back to inline on scroll up occurs at the wrong position.
