### ISSUE TITLE
How to change z-index 

### ISSUE THREAD

**Issue by AzadKshitij** [KyleAMathews/react-headroom#200]
I'm not able to understand How can I change z-index.?

**Comment by AzadKshitij** [comment]
Just found the solution in doc 😅😅
```css
.headroom {
  top: 0;
  left: 0;
  right: 0;
  z-index: 1;
}
.headroom--unfixed {
  position: relative;
  transform: translate3D(0, 0, 0);
}
.headroom--scrolled {
  transition: transform 200ms ease-in-out;
}
.headroom--unpinned {
  position: fixed;
  transform: translate3D(0, -100%, 0);
}
.headroom--pinned {
  position: fixed;
  transform: translate3D(0, 0, 0);
}
```
